saleor/saleor/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^$', views.details, name='details'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^password/reset/$', views.password_reset,
        name='reset-password'),
    url(r'^password/reset/done/$', django_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'),
        name='reset-password-done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',  # noqa
        views.password_reset_confirm, name='reset-password-confirm'),
    url(r'password/reset/complete/$', django_views.PasswordResetCompleteView.as_view(  # noqa
        template_name='account/password_reset_from_key_done.html'),
        name='reset-password-complete'),

    url(r'^address/(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^address/(?P<pk>\d+)/delete/$',
        views.address_delete, name='address-delete'),
    url(r'^delete/$', views.account_delete,
        name='delete'),
    url(r'^(?P<token>[0-9A-Za-z_\-]+)/delete-confirm/',
        views.account_delete_confirm, name='delete-confirm')]

saleor/saleor/dashboard/group/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.group_list, name='group-list'),
    url(r'^group-create/$', views.group_create, name='group-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.group_details, name='group-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.group_delete, name='group-delete')]

saleor/saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.menu_list, name='menu-list'),
    url(r'^add/$',
        views.menu_create, name='menu-add'),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        views.menu_edit, name='menu-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.menu_delete, name='menu-delete'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.menu_details, name='menu-details'),

    url(r'^(?P<menu_pk>[0-9]+)/add/$',
        views.menu_item_create, name='menu-item-add'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$',
        views.menu_item_create, name='menu-item-add'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$',
        views.menu_item_edit, name='menu-item-edit'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$',
        views.menu_item_delete, name='menu-item-delete'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$',
        views.menu_item_details, name='menu-item-details'),

    url(r'^(?P<menu_pk>[0-9]+)/items/reorder/$',
        views.ajax_reorder_menu_items, name='menu-items-reorder'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$',
        views.ajax_reorder_menu_items, name='menu-items-reorder'),
    url(r'^ajax/links/$',
        views.ajax_menu_links, name='ajax-menu-links')]

saleor/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^add/$', views.order_create, name='order-create'),
    url(r'^(?P<order_pk>\d+)/create/$',
        views.create_order_from_draft, name='create-order-from-draft'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.order_address, name='address-edit'),
    url(r'^(?P<order_pk>\d+)/edit-customer/$',
        views.order_customer_edit, name='order-customer-edit'),
    url(r'^(?P<order_pk>\d+)/remove-customer/$',
        views.order_customer_remove, name='order-customer-remove'),
    url(r'^(?P<order_pk>\d+)/edit-shipping/$',
        views.order_shipping_edit, name='order-shipping-edit'),
    url(r'^(?P<order_pk>\d+)/remove-shipping/$',
        views.order_shipping_remove, name='order-shipping-remove'),
    url(r'^(?P<order_pk>\d+)/edit-discount/$',
        views.order_discount_edit, name='order-discount-edit'),
    url(r'^(?P<order_pk>\d+)/edit-voucher/$',
        views.order_voucher_edit, name='order-voucher-edit'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.order_voucher_remove, name='order-voucher-remove'),
    url(r'^(?P<order_pk>\d+)/delete/$',
        views.remove_draft_order, name='draft-order-delete'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/add-variant/$',
        views.add_variant_to_order, name='add-variant-to-order'),
    url(r'^(?P<order_pk>\d+)/fulfill/$',
        views.fulfill_order_lines, name='fulfill-order-lines'),
    url(r'^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/cancel/$',
        views.cancel_fulfillment, name='fulfillment-cancel'),
    url(r'^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/tracking/$',
        views.change_fulfillment_tracking, name='fulfillment-change-tracking'),
    url(r'^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/packing-slips/$',  # noqa
        views.fulfillment_packing_slips, name='fulfillment-packing-slips'),
    url(r'^(?P<order_pk>\d+)/invoice/$',
        views.order_invoice, name='order-invoice'),
    url(r'^(?P<order_pk>\d+)/mark-as-paid/$',
        views.mark_order_as_paid, name='order-mark-as-paid'),

    url('^(?P<order_pk>\d+)/ajax/shipping-methods/$',
        views.ajax_order_shipping_methods_list,
        name='ajax-order-shipping-methods')]

saleor/saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.page_list, name='page-list'),
    url(r'^add/$', views.page_add, name='page-add'),
    url(r'^(?P<pk>[0-9]+)/$', views.page_details, name='page-details'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.page_update, name='page-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.page_delete, name='page-delete')]

saleor/saleor/dashboard/urls.py
from django.conf.urls import include, url

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .group.urls import urlpatterns as groups_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^collections/', include(collection_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^page/', include(page_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^groups/', include(groups_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^menu/', include(menu_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
    url(r'^search/', include(search_urls)),
    url(r'^taxes/', include(taxes_urls))]

saleor/saleor/search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search')]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import (
    cart_urlpatterns as cart_urls, checkout_urlpatterns as checkout_urls)
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.file_upload.views import FileUploadGraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

non_translatable_urlpatterns = [
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(FileUploadGraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))]

translatable_urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^page/', include((page_urls, 'page'), namespace='page')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'', include('payments.urls'))]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

saleor/saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils.translation import pgettext_lazy
from text_unidecode import unidecode

from ...product.models import Category
from ..seo.fields import SeoDescriptionField, SeoTitleField


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super().__init__(*args, **kwargs)
        self.fields['seo_description'] = SeoDescriptionField(
            extra_attrs={'data-bind': self['description'].auto_id})
        self.fields['seo_title'] = SeoTitleField(
            extra_attrs={'data-bind': self['name'].auto_id})

    class Meta:
        model = Category
        exclude = ['slug']
        labels = {
            'name': pgettext_lazy('Item name', 'Name'),
            'description': pgettext_lazy('Description', 'Description')}

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))
        if self.parent_pk:
            self.instance.parent = get_object_or_404(
                Category, pk=self.parent_pk)
        return super().save(commit=commit)

saleor/saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'categories': categories, 'filter_set': category_filter,
        'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-details', pk=root_pk)
        return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None, request.FILES or None, instance=category,
        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-details', pk=root_pk)
        return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.view_category')
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root,
           'filter_set': category_filter,
           'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-details', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-details', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

saleor/templates/dashboard/base_modal.html
{% load i18n %}

<form
  role="form" method="post" action="{% block action_url %}#!{% endblock %}"
  class="{% block form_class %}form-async{% endblock %}" novalidate>
  {% comment %}Empty form_class can be used for non-ajax forms with server redirect.{% endcomment %}
  {% csrf_token %}
  <div class="modal-content">
    <div class="row">
      <div class="col s12">
        <h5>
          {% block title %}{% endblock %}
        </h5>
      </div>
    </div>
    {% if form.non_field_errors %}
      <div class="col 12">
        {% for error in form.non_field_errors %}
          <p class="help-block materialize-red-text">{{ error }}</p>
        {% endfor %}
      </div>
    {% endif %}
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>
  <div class="modal-footer">
    <span class="left">
      {% block actions_left %}{% endblock %}
    </span>
    <a href="#!" class="modal-action modal-close btn-flat waves-effect">
      {% block cancel_action %} {% trans "Cancel" context "Dashboard cancel action" %} {% endblock %}
    </a>
    <button type="submit" class="modal-action btn-flat waves-effect">
      {% block primary_action %}{% endblock %}
    </button>
  </div>
</form>

saleor/templates/dashboard/base_zero_page.html
<div class="card zero-page">
  <div class="card-content">
    <div class="zero-page__title">
      {% block title %}{% endblock %}
    </div>
    <div class="zero-page__content">{% block content %}{% endblock %}</div>
  </div>
</div>

saleor/templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load price from taxed_prices %}
{% load status %}

{% block title %}
  {{ block.super }}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="data-table-header{% if not preauthorized_payments %} data-table-header--no-data{% endif %}">
          <span class="data-table-title" title="{% blocktrans trimmed with counter=preauthorized_payments.count context "Dashboard homepage summary header title" %}Showing last {{ counter }} results{% endblocktrans %}">
            {% trans "Preauthorized payments" context "Dashboard homepage table title" %}
          </span>
        </div>
        {% if preauthorized_payments %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  <th>
                    {% trans "Order" context "Preauthorized payments table header" %}
                  </th>
                  <th>
                    {% trans "Date" context "Preauthorized payments table header" %}
                  </th>
                  <th>
                    {% trans "Customer" context "Preauthorized payments table header" %}
                  </th>
                  <th class="right-align">
                    {% trans "Amount" context "Preauthorized payments table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for payment in preauthorized_payments %}
                  <tr data-action-go="{% url "dashboard:order-details" order_pk=payment.order.pk %}">
                    <td>
                      {{ payment.order }}
                    </td>
                    <td>
                      {{ payment.created }}
                    </td>
                    <td>
                      {{ payment.order.user|default:_("Guest") }}
                    </td>
                    <td class="right-align">
                      {% price payment.get_total_price.gross %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data not-found">
            <p class="grey-text">
              {% trans "No preauthorized payments." context "Empty Preauthorized payments table message" %}
            </p>
          </div>
        {% endif %}
      </div>

      <div class="card">
        <div class="data-table-header{% if not orders_to_ship %} data-table-header--no-data{% endif %}">
          <span class="data-table-title" title="{% blocktrans trimmed with counter=orders_to_ship|length context "Dashboard homepage summary header title" %}Showing last {{ counter }} results{% endblocktrans %}">
            {% trans "Orders ready for shipment" context "Dashboard homepage table title" %}
          </span>
        </div>
        {% if orders_to_ship %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table last-right-align">
              <thead>
                <tr>
                  <th>
                    #
                  </th>
                  <th></th>
                  <th>
                    {% trans "Customer" context "Orders table header" %}
                  </th>
                  <th>
                    {% trans "Placed on" context "Orders table header" %}
                  </th>
                  <th>
                    {% trans "Payment status" context "Orders table header" %}
                  </th>
                  <th>
                    {% trans "Total" context "Orders table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for order in orders_to_ship %}
                  <tr data-action-go="{% url 'dashboard:order-details' order_pk=order.pk %}">
                    <td>
                      #{{ order.id }}
                    </td>
                    <td>
                      {% render_order_status order.status order.get_status_display %}
                    </td>
                    {% trans "Guest" context "Anonymous user account value" as guest %}
                    <td>
                      {{ order.user|default:guest }}
                    </td>
                    <td>
                      {{ order.created }}
                    </td>
                    <td>
                      {% render_status order.get_last_payment_status order.get_last_payment_status_display %}
                    </td>
                    <td class="right-align">
                      {% price order.total.gross %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data not-found ">
            <p class="grey-text">
              {% trans "No orders are ready for shipment." context "Empty order table message" %}
            </p>
          </div>
        {% endif %}
      </div>
      <div class="card">
        <div class="data-table-header{% if not low_stock %} data-table-header--no-data{% endif %}">
          <span class="data-table-title" title="{% blocktrans trimmed with counter=low_stock.count context "Dashboard homepage summary header title" %}Showing last {{ counter }} results{% endblocktrans %}">
            {% trans "Products with low stock" context "Dashboard homepage table title" %}
          </span>
        </div>
        {% if low_stock %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  <th>
                    {% trans "Product name" context "Low stock product list" %}
                  </th>
                  <th class="right-align">
                    {% trans "Stock left" context "Low stock product list" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for product in low_stock %}
                  <tr data-action-go="{% url "dashboard:product-details" pk=product.pk %}">
                    <td>
                      {{ product }}
                    </td>
                    <td class="right-align">
                      {{ product.total_stock }}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data not-found">
            <p class="grey-text">
              {% trans "No products are low in stock." context "Empty low stock table message" %}
            </p>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}